# Generated by Django 5.0.6 on 2024-06-15 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_streamplatfrom_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='StreamingPlatform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.streamplatfrom'),
            preserve_default=False,
        ),
    ]
