# Generated by Django 5.0.6 on 2024-06-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='review_user',
        ),
    ]
